extends Node


var paused = false

onready var tiles = [
[preload("res://tiles/blueGrid.tscn"), preload("res://menu/icons/temp/blue_grad.png"), "Blue Cube"],
[preload("res://tiles/greenGrid.tscn"), preload("res://menu/icons/temp/green_grad.png"), "Green Cube"], 
[preload("res://tiles/redGrid.tscn"), preload("res://menu/icons/temp/red_oval.png"), "Red Oval"],
[preload("res://tiles/greyGrid.tscn"), preload("res://menu/icons/temp/grey_grad.png"), "Grey Cat"],
[preload("res://tiles/genericForest/appleTree1.tscn"), preload("res://assets/genericForest/icons/appleTree.png"), "Apple Tree 1"],
[preload("res://tiles/genericForest/appleTree2.tscn"), preload("res://assets/genericForest/icons/appleTree.png"), "Apple Tree 2"],
[preload("res://tiles/genericForest/GrassFlat.tscn"), preload("res://assets/genericForest/icons/grassFlat.png"), "Grass Flat"],
[preload("res://tiles/genericForest/GrassSlope.tscn"), preload("res://assets/genericForest/icons/grassSlope.png"), "Grass Slope"],
[preload("res://tiles/genericForest/GrassSlopeOutwards.tscn"), preload("res://assets/genericForest/icons/grassSlopeOutwards.png"), "Grass Slope Outwards"],
[preload("res://tiles/genericForest/GrassSlopeInwards.tscn"), preload("res://assets/genericForest/icons/grassSlopeInwards.png"), "Grass Slope Inwards"],
[preload("res://tiles/genericForest/GrassFlatEndDirt.tscn"), preload("res://assets/genericForest/icons/grassFlatEndDirt.png"), "Grass Flat End Dirt"],
[preload("res://tiles/genericForest/GrassDirtPatch.tscn"), preload("res://assets/genericForest/icons/grassDirtPatch.png"), "Grass Dirt Patch"],
[preload("res://tiles/genericForest/GrassFlatCurveInwardsDirt.tscn"), preload("res://assets/genericForest/icons/grassFlatCurveInwardsDirt.png"), "Grass Flat Curve Inwards Dirt"],
[preload("res://tiles/genericForest/GrassFlatCurveOutwardsDirt.tscn"), preload("res://assets/genericForest/icons/grassFlatCurveOutwardsDirt.png"), "Grass Flat Curve Outwards Dirt"],
[preload("res://tiles/genericForest/dirtSlopeOutwards.tscn"), preload("res://assets/genericForest/icons/dirtSlopeOutwards.png"), "Dirt Slope Outwards"],
[preload("res://tiles/genericForest/dirtSlopeInwards.tscn"), preload("res://assets/genericForest/icons/dirtSlopeInwards.png"), "Dirt Slope Inwards"],
[preload("res://tiles/genericForest/dirtSlopeGrass.tscn"), preload("res://assets/genericForest/icons/dirtSlopeGrass.png"), "Dirt Slope Grass"],
[preload("res://tiles/genericForest/dirtSlopeGrass2.tscn"), preload("res://assets/genericForest/icons/dirtSlopeGrass2.png"), "Dirt Slope Grass 2"],
[preload("res://tiles/genericForest/dirtSlope.tscn"), preload("res://assets/genericForest/icons/dirtSlope.png"), "Dirt Slope"],
[preload("res://tiles/genericForest/dirtGrassPatch.tscn"), preload("res://assets/genericForest/icons/dirtGrassPatch.png"), "Dirt Grass Patch"],
[preload("res://tiles/genericForest/dirtBlock.tscn"), preload("res://assets/genericForest/icons/dirtBlock.png"), "Dirt Block"],
[preload("res://tiles/genericForest/dirt2GrassFlatPath.tscn"), preload("res://assets/genericForest/icons/dirt2GrassFlatPath.png"), "Dirt 2 Grass Flat Path"],
[preload("res://tiles/genericForest/dirt2GrassFlatPathEnd.tscn"), preload("res://assets/genericForest/icons/dirt2GrassFlatPathEnd.png"), "Dirt 2 Grass Flat Path End"],
[preload("res://tiles/genericForest/dirt2GrassFlat.tscn"), preload("res://assets/genericForest/icons/dirt2GrassFlat.png"), "Dirt 2 Grass Flat"],
[preload("res://tiles/genericForest/decBushFull.tscn"), preload("res://assets/genericForest/icons/decBushFull.png"), "Decoration Bush Full"],
[preload("res://tiles/genericForest/decBushMed.tscn"), preload("res://assets/genericForest/icons/decBushMed.png"), "Decoration Bush Medium"],
[preload("res://tiles/genericForest/decBushSmall.tscn"), preload("res://assets/genericForest/icons/decBushSmall.png"), "Decoration Bush Small"],
[preload("res://tiles/genericForest/decDarkGrass.tscn"), preload("res://assets/genericForest/icons/decGrassDark.png"), "Decoration Dark Grass"],
[preload("res://tiles/genericForest/decDirt.tscn"), preload("res://assets/genericForest/icons/decDirt.png"), "Decoration Dirt"],
[preload("res://tiles/genericForest/decDirtPile.tscn"), preload("res://assets/genericForest/icons/decDirtPile.png"), "Decoration Dirt Pile"],
[preload("res://tiles/genericForest/decGrass.tscn"), preload("res://assets/genericForest/icons/decGrass.png"), "Decoration Grass"],
[preload("res://tiles/genericForest/decLightGrass.tscn"), preload("res://assets/genericForest/icons/decGrassLight.png"), "Decoration Light Grass"],
[preload("res://tiles/genericForest/decLog.tscn"), preload("res://assets/genericForest/icons/decLog.png"), "Decoration Log"],
[preload("res://tiles/genericForest/decPebbles.tscn"), preload("res://assets/genericForest/icons/decPebbles.png"), "Decoration Pebbles"],
[preload("res://tiles/genericForest/decRedFlowers.tscn"), preload("res://assets/genericForest/icons/decRedFlowers.png"), "Decoration Red Flowers"],
[preload("res://tiles/genericForest/decRocks.tscn"), preload("res://assets/genericForest/icons/decRocks.png"), "Decoration Rocks"],
[preload("res://tiles/genericForest/decShell.tscn"), preload("res://assets/genericForest/icons/decShells.png"), "Decoration Shell"],
[preload("res://tiles/genericForest/decVines1.tscn"), preload("res://assets/genericForest/icons/decVines1.png"), "Decoration Vines 1"],
[preload("res://tiles/genericForest/decVines2.tscn"), preload("res://assets/genericForest/icons/decVines2.png"), "Decoration Vines 2"],
[preload("res://tiles/genericForest/decYellowFlowers.tscn"), preload("res://assets/genericForest/icons/decYellowFlowers.png"), "Decoration Yellow Flowers"]
]
